[package]
name = "mountpoints"
version = "0.1.0"
edition = "2018"

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["errhandlingapi", "handleapi", "fileapi", "winerror"] }
